### ISSUE TITLE
Style props and z-index on ReactQueryDevtools

### ISSUE THREAD

**Issue by nicoqh** [tannerlinsley/react-query-devtools#10]
Hi!

The `ReactQueryDevtools` component has a fixed position, but no z-index. Certain elements of a user's app may be displayed on top of the devtools. The same applies to the two buttons (open and close).

I can open a PR that sets `zIndex: '99999'` on all three elements, unless you want to do it differently.

Thanks for publishing this library!

**Comment by tannerlinsley** [comment]
I would accept a PR that’s adds support for a style prop to be proxied from the dev tools component to the underlying buttons and panel. Thoughts?

**Comment by nicoqh** [comment]
Do you mean having a single style prop on `ReactQueryDevtools` that is proxied to all three elements? Wouldn't that only allow for adding the same styles to all three? Also, would you want the existing styles to be merged?

Regardless, I still think there should be a z-index on the `ReactQueryDevtools` by default. Its position is fixed, and I think a z-index is just as natural as the bottom, right, width, height attributes. (If you agree with this, I can do this PR first.)

**Comment by tibotiber** [comment]
Hi there, 

Any progress on this?

If @nicoqh is not working on it, I'd be keen to open a PR to set the styles as I would like to move the 🎛 button myself. There are 3 elements to potentially style, I'd suggest 3 props `panelStyle`, `closeButtonStyle` and `openButtonStyle`. Do you have better ideas or names?

If that's also ok, I agree with having `zIndex: '99999'` in the default styles, but not in favor of having a separate prop for zIndex, the styles prop will be good enough.

Let me know! Cheers.

**Comment by nicoqh** [comment]
I haven't done anything yet because I wanted to wait for Tanner's approval.

But I like your suggestion, @tibotiber, and agree that zIndex should not be another prop (though the component should have a zIndex by default, due to its position being fixed).

I can rename the issue to something more appropriate if you decide to make a PR against it.

**Comment by tannerlinsley** [comment]
Yeah, I think it would be fine adding props for each element that get forwarded to each one. Also adding the default z-index to those props :) Go for it!

**Comment by tibotiber** [comment]
Cool, thanks for the answers. I've opened #13.
