### ISSUE TITLE
useMutation needs a safeDispatch

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/react-query-devtools#11]
I'm getting `Warning: Can't perform a React state update on an unmounted component.` when the mutation results in the component getting unmounted. Here's a ridiculously simplified example:

https://codesandbox.io/s/bold-colden-bztuq

```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import {useMutation} from 'react-query'

function Child({doMutation}) {
  const [mutate] = useMutation(doMutation)
  return <button onClick={mutate}>mutate</button>
}

function App() {
  const [renderChild, setRenderChild] = React.useState(true)
  return renderChild ? (
    <Child doMutation={() => setRenderChild(false)} />
  ) : (
    'no child'
  )
}

ReactDOM.render(<App />, document.getElementById('root'))
```

I'm seeing this in [my bookshelf app](https://github.com/kentcdodds/bookshelf/blob/c3e971c2a9ea057e690825c1602a41723af7ffbf/src/components/status-buttons.js#L59-L93).

FWIW, here's how I side-step this problem:

```javascript
function useSafeDispatch(dispatch) {
  const mounted = React.useRef(false)
  React.useLayoutEffect(() => {
    mounted.current = true
    return () => (mounted.current = false)
  }, [])
  return React.useCallback(
    (...args) => (mounted.current ? dispatch(...args) : void 0),
    [dispatch],
  )
}

// ...
  const [state, realDispatch] = React.useReducer(...)
  const dispatch = useSafeDispatch(realDispatch)
```

**Comment by tannerlinsley** [comment]
I've fixed this in React Query and release it. Do have any reason to believe that this issue was also present in the devtools itslef?

**Comment by kentcdodds** [comment]
No, I didn't have them installed.

**Comment by tannerlinsley** [comment]
Oh. Any important reason this was created here and not on the main repo?

**Comment by kentcdodds** [comment]
lol, that was a mistake 😅

**Comment by tannerlinsley** [comment]
😁🤘
