### ISSUE TITLE
"react-query" missing from dependencies (Yarn PnP)

### ISSUE THREAD

**Issue by dgreuel** [tannerlinsley/react-query-devtools#14]
When trying to use this package with Yarn Plug'n'Play enabled, I get an error because `react-query` is not listed in the package dependencies:

```Module not found: Package "react-query-devtools@1.1.0" (via "/Users/dgreuel/Library/Caches/Yarn/v6/npm-react-query-devtools-1.1.0-95d4ebea3669e727e0529eb5ebc097f6aed81bed-integrity/node_modules/react-query-devtools/dist/react-query-devtools.development.js") is trying to require the package "react-query" (via "react-query") without it being listed in its dependencies (react, react-query-devtools)```

**Comment by tannerlinsley** [comment]
Fixed in latest version
