### ISSUE TITLE
Empty panel in 1.1.2

### ISSUE THREAD

**Issue by denisborovikov** [tannerlinsley/react-query-devtools#16]
After upgrade from 1.1.1 to 1.1.2 there're no queries in the devtools.

Downgrade to 1.1.1 makes it work again.

**Comment by denisborovikov** [comment]
It's kinda weird but codesandbox's example seems working fine with 1.1.2.

**Comment by denisborovikov** [comment]
Moving `react-query` back to `peerDependencies` and removing `node_modules/react-query-devtools/node_modules` made it work in my case.

**Comment by tannerlinsley** [comment]
Ah. It’s the last commit to fix plug n play. Will you submit a PR for your change back to a peer deep?

**Comment by denisborovikov** [comment]
Sure, here you go https://github.com/tannerlinsley/react-query-devtools/pull/17
