### ISSUE TITLE
Dev dependencies 

### ISSUE THREAD

**Issue by abdelrahmanahmed** [tannerlinsley/react-query-devtools#24]
Very awesome package, Question from my side, you mentioned in the documentation that this package will be installed in the dependencies, this is a debugging tool and i believe this should be installed in the dev dependencies, am i right?

**Comment by tannerlinsley** [comment]
From the docs:

> By default, React Query Devtools are not imported and used when process.env.NODE_ENV === 'production', so you don't need to worry about excluding them during a production build.

> If you want to use the devtools in production, you can manually import them (preferably asynchronously code-split) by importing the dist/react-query-devtools.production.min.js file directly.
