### ISSUE TITLE
Error click on query to return query's  details

### ISSUE THREAD

**Issue by aabeborn** [tannerlinsley/react-query-devtools#28]
When i click on the query to retriving the details this error shows:
<img width="1478" alt="Schermata 2020-05-29 alle 12 34 21" src="https://user-images.githubusercontent.com/26009890/83251051-52dd4800-a1a9-11ea-9f60-34a3b04f842e.png">
<img width="1478" alt="Schermata 2020-05-29 alle 12 34 33" src="https://user-images.githubusercontent.com/26009890/83251639-2d9d0980-a1aa-11ea-89fd-321c4dc30936.png">

**Comment by nseptier** [comment]
Pretty sure it's fixed in https://github.com/tannerlinsley/react-query-devtools/pull/27. It just needs to be released.

**Comment by kamranayub** [comment]
~I think it is released, I am using `1.1.16` which _should_ include the fix but I'm seeing it too @tannerlinsley~ NEVERMIND, had to restart the dev server after upgrading 🤦 

This should be released and fixed.

**Comment by tannerlinsley** [comment]
Nice!
