### ISSUE TITLE
How do I inspect mutations with the devtools?

### ISSUE THREAD

**Issue by fev4** [tannerlinsley/react-query-devtools#31]
Hi,

Just getting started with react-query and I'm finding it awesome!

I'm currently using graphql-request and with every mutation I get data back, for example the id of a newly created user (from a DB like Fauna) and things like that. How can I inspect useMutation within the devtools?

I  can only seem to inspect queries

Thanks in advance for any help/info!

**Comment by changyeamoon** [comment]
@fillipvt I also don't see the option !

**Comment by tannerlinsley** [comment]
This is currently not possible. You’ll be better of inspecting your mutations though the chrome devtools network panel for now.

**Comment by bbrinx** [comment]
@tannerlinsley this would be a great feature. Are there any plans on implementing mutation inspection?

**Comment by tannerlinsley** [comment]
I would be open to discussing what exactly you would want to see in such a UI. Most often, mutations are outgoing through the network panel, so I don't see what you would gain on top of what you can see in your browser devtools?

**Comment by bbrinx** [comment]
Not quite sure I know what you mean. What's the difference between queries and mutations in regards to devtools vs. network panel?

**Comment by tannerlinsley** [comment]
Queries have data and state that are stored in a global cache, hidden from the developer unless you use the React Query Devtools to see them.

Mutations do not have any data or state that is "hidden" from you the developer and that data/state is not global. This means that there isn't really any data for React Query Devtools to inspect.

The Browser devtools however show you all of the incoming and outgoing network transmissions and is a much better place to inspect what your mutations are actually sending to the server.
