### ISSUE TITLE
Proposed many-to-many extension

### ISSUE THREAD

**Issue by lukaszmakuch** [tannerlinsley/react-query-devtools#33]
Hi! 👋

Thank you for creating react-query. It's full of good ideas! 👍

I'm creating this issue to discuss the possibility of enhancing the API so that it can support many-to-many relations.

I believe that a snippet says a thousand words, so let's assume we have two functions:
1. fetchUsers returning a page of users (with the IDs of their "badges")
2. fetchBadge which gives a badge by ID

A page of users looks like this:
```
[
  {
    id: 1,
    name: "Katie",
    badgesIds: [1, 2, 3]
  },
  {
    id: 2,
    name: "John",
    badgesIds: [1, 3, 9]
  },
  {
    id: 3,
    name: "Tommy",
    badgesIds: [3, 1]
  }
]
```

And this is what a badge looks like:
```
{ id: 2, color: "#0f0", name: "2nd badge" }
```

In my component I want to join the results to make them look like:
```
[
  {
    id: 1,
    name: "Katie",
    badges: [
      { id: 1, color: "#f00", name: "The First Badge" },
      { id: 2, color: "#0f0", name: "2nd badge" },
      { id: 3, color: "#00f", name: "The Third Thing" }
    ]
  },
  {
    id: 2,
    name: "John",
    badges: [
      { id: 1, color: "#f00", name: "The First Badge" },
      { id: 3, color: "#00f", name: "The Third Thing" },
      { id: 9, color: "#f0f", name: "9nth" }
    ]
  },
  {
    id: 3,
    name: "Tommy",
    badges: [
      { id: 3, color: "#00f", name: "The Third Thing" },
      { id: 1, color: "#f00", name: "The First Badge" }
    ]
  }
]
```

I can easily get a page of users:
```
const {data: fetchedUsers} = useQuery(['users', page], fetchUsers);
```

Extracting the list of badges IDs is easy:

```
const badgesIds = _.uniq(fetchedUsers.flatMap(user => user.badgesIds));
```

The only thing I'm missing is a way to use multiple queries, something like that:

```
const badges = useQueries(badgesIds.map(id => ['badge', id]), fetchBadge);
```

This is just an example, but it illustrates a need I keep running into.

Of course it'd be nicer to have a front-end-oriented back-end endpoint to avoid the whole overhead of front-end joins, but sadly it's not always the case.

I could merge `fetchUsers` with `fetchBadges`, but then I wouldn't be able to to capitalize on react-query's cache and request deduplication.

How do you think, is there room for `useQueries` in react-query?

Cheers!

**Comment by tannerlinsley** [comment]
This belongs in the discussion tab on the actual React Query repository. Please post this discussion there.
