### ISSUE TITLE
View state and server data related state events in devtools

### ISSUE THREAD

**Issue by dudiharush** [tannerlinsley/react-query-devtools#34]
Hi, could you somehow integrate redux dispatch actions into the event log of this devtool, so the order of events from redux and react query is kept? Now i need to look at both devtools, but i loose the order of the events. Thanks!

**Comment by tannerlinsley** [comment]
The data in the devtools is not historical. If you need to debug historical events of queries, you can dispatch dummy Redux events in your Queries and components.
