### ISSUE TITLE
Non scrollable query list

### ISSUE THREAD

**Issue by LandazuriPaul** [tannerlinsley/react-query-devtools#42]
Hey!

I just discovered this devtools projects for the `react-query` library. And it seems really nice! Thank you very much for all the hard work!

As I wanted to use it to debug an application I'm working on, I noticed that the general query list is not scrollable.

To illustrate this, here is a screenshot I took while using the [demo](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/playground):

<img width="1440" alt="Screenshot 2020-07-15 at 17 34 53" src="https://user-images.githubusercontent.com/5787964/87571270-b07a1500-c6c1-11ea-96b8-7b914cce4099.png">

In order to make it observable, I had to reduce a lot the size of the browser window as the demo doesn't use many queries. But when working on a slightly bigger application with around 12 queries registered by the dev tools, we can't browse them.

As a simple workaround, I just manually forced the main container to have its overflow set to `auto`. But I reckon that the desired effect would be to only have the query list scrolling.

Have a great one!

**Comment by cliffordp** [comment]
Same. 45s demo: https://share.getcloudapp.com/YEupn2w4

**Comment by tannerlinsley** [comment]
I’ll get this fixed ASAP

**Comment by LandazuriPaul** [comment]
Oh thank you for the quick response! Let me know if I can help with this.

**Comment by kamranayub** [comment]
@tannerlinsley Have a fix ready for you if you like!

**Comment by LandazuriPaul** [comment]
Thank you for your promptness and nice fix @kamranayub and @tannerlinsley!

Have a great weekend :)
