### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by asifsaho** [tannerlinsley/react-query-devtools#5]
Is it possible to use with TypeScript?

**Comment by tannerlinsley** [comment]
Yep. Just no types.

**Comment by epeterson320** [comment]
I was able to get by with putting this in my **react-app-env.d.ts**. You can use a similar declaration file as you see fit.
```typescript
declare module 'react-query-devtools' {
  const ReactQueryDevtools: React.ComponentType<{
    initialIsOpen?: boolean;
    position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
    closeButtonProps?: JSX.IntrinsicElements['button'];
    toggleButtonProps?: JSX.IntrinsicAttributes['button'];
    panelProps?: JSX.IntrinsicAttributes['div'];
  }>;
}
```

**Comment by tannerlinsley** [comment]
I would accept a PR to add this to the library :)

**Comment by tannerlinsley** [comment]
Or even better, just a PR that migrates the source to TS using the same setup as React Query itself.

**Comment by epeterson320** [comment]
I just checked, and the library has had typescript support for a while. I'm just on an old version and need to upgrade, so I'm  glad I checked!
