### ISSUE TITLE
Can't explore items in ReactQueryDevtools 

### ISSUE THREAD

**Issue by yanislavgalyov** [tannerlinsley/react-query-devtools#50]
**Describe the bug**
Trying to open a item in ReactQueryDevtools component results in an error 
`
TypeError
Converting circular structure to JSON
    --> starting at object with constructor 'Query'
    |     property 'queryCache' -> object with constructor 'QueryCache'
    |     property 'queries' -> object with constructor 'Object'
    --- property '["repoData"]' closes the circle
`

**To Reproduce**
1. Open [https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/simple](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/simple)
2. Click on `repoData` item in ReactQueryDevtools component
3. See error 😒 

**Expected behavior**
A working ReactQueryDevtools component as in [this](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/playground) example.

**Screenshots**
![hm](https://user-images.githubusercontent.com/3160280/88886410-111d5c00-d243-11ea-8fcd-aeaa916f8a5c.PNG)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: chrome

**Additional context**
I have a very small demo react app with a very simple fetching of object `{id: 1}` which reproduces this errror.

**Comment by kachkaev** [comment]
I just followed repro steps in FF and Chrome on macOS and did not see the error 🤔

**Comment by yanislavgalyov** [comment]
This issue is fixed on 2.4.2 with this [commmit](https://github.com/tannerlinsley/react-query-devtools/commit/c1b4a53dca52e0731958da64bb6f037b42b86079). 

But on 2.4.1 is still reproducable. Anyway I'm closing this and thanks to @tannerlinsley for addressing it.
