### ISSUE TITLE
Query details disappear when page width is < 1000px

### ISSUE THREAD

**Issue by kachkaev** [tannerlinsley/react-query-devtools#52]
It seems like there is not enough space for Query Details when the page is narrower than 1000px and there are quite a few queries to show. According to the browser devtools, the pane ends up being pushed below the whole panel.

![Screenshot 2020-07-08 at 16 21 24](https://user-images.githubusercontent.com/608862/89465059-65579d00-d769-11ea-9624-eea426295a89.gif)

## Expected behaviour

When page width is less than 1000px, query details should be below the list regardless of how many queries it contains.

**Comment by kachkaev** [comment]
It looks like this issue was caused by b10a9622211d45013bdcea5be5c712fb4880160c. See `flex: '1 1 50%',` →  `flex: '1 1 500px'` and a couple of related changes.

**Comment by tannerlinsley** [comment]
This is now fixed!
