### ISSUE TITLE
Query data under the data explorer section is showing up as null

### ISSUE THREAD

**Issue by andrewli-ca** [tannerlinsley/react-query-devtools#55]
When using query data to seed future queries, the approach from section 23 of react-query-essentials is to iterate through each item and call `setQueryData` on each one of them. This works as intended but opening up the dev tools to inspect the queries, the data for each query is showing up as null. This looks like a bug because the data is being read from the cache and is being rendered on to the screen.

![image](https://user-images.githubusercontent.com/9060674/89727602-4102f700-d9db-11ea-9b24-cd519ad27f98.png)

It looks to me that the changes made after 2.5.6 of react-query are not playing nicely with react-query-devtools. Version 2.5.6 of react-query works with react-query-devtools with no issues.

![image](https://user-images.githubusercontent.com/9060674/89727722-3bf27780-d9dc-11ea-968f-ffb77763d190.png)

CodeSandbox (using latest version of react-query and react-query-devtools)
https://i58su.csb.app
https://codesandbox.io/s/23-using-query-data-to-seed-future-queries-i58su?file=/src/index.js

**Comment by tannerlinsley** [comment]
This is now fixed!
