### ISSUE TITLE
Add the name of the component or function that initiated the query

### ISSUE THREAD

**Issue by AlonGvili** [tannerlinsley/react-query-devtools#56]
I think it will be easier to debug queries if I knew who initiated them,  for example I have a couple of components that use the same query and passed it different props using useParams from react-router-dom, and if I forget to convert from string to number I get non-working query in the dev tools.

**Comment by tannerlinsley** [comment]
This would be a ton of work IMO for very little return. I'm open if you would like to submit a PR for this, but I don't plan on implementing this any time soon.

**Comment by AlonGvili** [comment]
Thanks for your answer
