### ISSUE TITLE
Type error: cannot read length of undefined

### ISSUE THREAD

**Issue by Buuntu** [tannerlinsley/react-query-devtools#57]
Getting this error even in a codesandbox with latest react-query and react-query-devtools:

```
TypeError
Cannot read property 'length' of undefined
```

It works fine if I turn off react-query-devtools.

I've tried with the panel inside ReactQueryConfigProvider and outside and it makes no difference.

Example:
https://codesandbox.io/s/react-query-devtools-example-broken-vlzxv?file=/src/index.tsx

**Comment by Buuntu** [comment]
Looks like if you downgrade to react-query 2.6.0 this stops being a problem.

**Comment by ingro** [comment]
I have the same issue too, seems indeed related to the latest release of react-query (2.7.0)

**Comment by sarbazx** [comment]
> Looks like if you downgrade to react-query 2.6.0 this stops being a problem.

I tried downgrading to 2.6.0 but still getting this error, any ideas?

**Comment by Buuntu** [comment]
> > Looks like if you downgrade to react-query 2.6.0 this stops being a problem.
> 
> I tried downgrading to 2.6.0 but still getting this error, any ideas?

Look at the sandbox example above.  If you fork it and change to 2.6.0 it works, so maybe just use that as a template?

**Comment by arthur-zhuk** [comment]
We need a fix for this ASAP.

**Comment by tannerlinsley** [comment]
Fixed in the latest version of devtools

**Comment by senadir** [comment]
was that version released yet? @tannerlinsley

**Comment by tannerlinsley** [comment]
Yep!

Tanner Linsley

**Comment by GennadiiFairushin** [comment]
@senadir I guess it is "react-query": "^3.0.1", which is not not tagged as `latest`

**Comment by tannerlinsley** [comment]
No, 3.0.1 was a mis-release. Please always use the latest tag to resolve.

**Comment by IDrissAitHafid** [comment]
I get the same error on 2.4.4.

**Comment by silloi** [comment]
I got the same error about `getQueryOpacity()` on 2.4.7.

```
TypeError: Cannot read property 'length' of undefined
getQueryOpacity
src/utils.js:23
  20 | }
  21 | 
  22 | export function getQueryOpacity(query) {
> 23 |   return !query.observers.length ? 0.3 : 1
  24 | }
  25 | 
  26 | export function getQueryStatusLabel(query) {
```

**Comment by silloi** [comment]
Oops I upgraded the version of *react-query* to the latest 2.15.4 then it works. Thank you anyway.
