### ISSUE TITLE
the query status in devtool is not correct

### ISSUE THREAD

**Issue by TIS-OMiddle** [tannerlinsley/react-query-devtools#61]
## Step
codesandbox: https://codesandbox.io/s/rq-devtool-f1e0z?file=/src/index.js

click the "switch" button and see the status. The latest query status is always `fresh`, but `react-query` work fine.

## Expect
If `staleTime` is not setted, `status` shoule be `stale` immediately according to the document. But now even I set the `staleTime` to 1000, it still shows `fresh`.

By the way, it work fine with `react-query@2.12.1`

## version
react-query: 2.13.0
react-query-devtools: 2.4.5

## screen shot
![image](https://user-images.githubusercontent.com/24486385/91839955-7f11d480-ec82-11ea-88a9-06ea2553d3fb.png)
![image](https://user-images.githubusercontent.com/24486385/91840000-8e911d80-ec82-11ea-922e-187711d4089e.png)

**Comment by tannerlinsley** [comment]
The latest versions of both libraries should be fixed to work with each other.

**Comment by matthewdavidson** [comment]
I forked the codesandbox repo above and updated the package.json to latest versions (react-query: ^2.14.1, react-query-devtools: ^2.4.5) and the dev tools are still reporting the wrong query status.

https://codesandbox.io/s/rq-devtool-forked-v8zwn

<img width="1911" alt="Screenshot 2020-09-03 at 11 03 23" src="https://user-images.githubusercontent.com/1440090/92101577-3c144600-edd5-11ea-894c-d4a020f25354.png">
