### ISSUE TITLE
Dev tools close on resize

### ISSUE THREAD

**Issue by mattcorner** [tannerlinsley/react-query-devtools#62]
I'm having an issue where the dev tools close any time I try and resize them in an app I am working on.

In the demo, it occurs when the user is scrolled to the bottom of the page and attempts to resize. See gif for reproduction.

![react-query-devtools-resize-bug](https://user-images.githubusercontent.com/27866636/91852303-8a500a80-ec58-11ea-9568-c69d47dd85a8.gif)

**Comment by tannerlinsley** [comment]
Fixed in v3
