### ISSUE TITLE
Doesn't work if placed above ReactQueryCacheProvider in app tree

### ISSUE THREAD

**Issue by avaragado** [tannerlinsley/react-query-devtools#67]
I started using react-query and react-query-devtools today, and followed the instructions at https://react-query.tanstack.com/docs/quick-start (which, without discussion, indicates you should put `ReactQueryCacheProvider` at the root of the app).

I also followed the instructions at https://github.com/tannerlinsley/react-query-devtools, which say "Place the following code as high in your React app as you can. The closer it is to the root of the page, the better it will work!". No mention of `ReactQueryCacheProvider`.

You can guess what happens next...

I put `ReactQueryCacheProvider` at the root of the app, and made `ReactQueryDevTools` its sibling. And `ReactQueryDevTools` displayed fine, but ignored my test query. The test query itself worked.

When I moved `ReactQueryDevTools` under `ReactQueryCacheProvider`, the dev tools spotted my test query successfully.

I don't know whether `ReactQueryCacheProvider` is required or not - the doc isn't clear - but it would be worth saying in the react-query-devtools doc at least that `ReactQueryDevTools` needs to be below `ReactQueryCacheProvider` in the app tree.

Obvious perhaps, but I followed the instructions to the letter!

**Comment by tannerlinsley** [comment]
Looks like we need to do one of the following:
- Use a portal and require/document that the component be placed in the context
- Support placing the devtools outside of the component and magically link them up
- Support providing the queryCache to the devtools (I kinda like this idea)

@boschni Thoughts?

**Comment by boschni** [comment]
I also like the third option most. Then you can either wrap `ReactQueryDevTools` within `ReactQueryCacheProvider` or explicitly provide the `QueryCache` to it.

**Comment by mikecousins** [comment]
Third option is my vote as well. I just ran into this today.

**Comment by ChathurangaKCD** [comment]
I like the third option.  I'm using multiple react-query versions under yarn aliases ( migrating from previous versions ). Currently `queryCache` is imported from "react-query", Instead I would like to import `queryCache` from a different alias, and provide it devtools.

**Comment by tannerlinsley** [comment]
If this is still an issue for you, please reopen in the React Query repository.
