### ISSUE TITLE
Add way to render Iterable objects that aren't arrays (Map, Set, etc..)

### ISSUE THREAD

**Issue by JimmayVV** [tannerlinsley/react-query-devtools#71]
It would be great if we could render data sets that are Iterable, but are not arrays. Specifically in mind I have Maps, and Sets, but obviously there are others as well.

I [volunteered to submit a PR](https://twitter.com/JimmayVV/status/1314583393573785604) for this on Twitter, and I intend to do so, but I wanted to have an issue to link to when I did so.

**Comment by JimmayVV** [comment]
.

**Comment by JimmayVV** [comment]
Wait, I jumped the gun. I'll let GitHub handle this one

**Comment by tannerlinsley** [comment]
If this is still an issue, please reopen on the React Query repository.
