### ISSUE TITLE
Resized container height is reset after refresh

### ISSUE THREAD

**Issue by Idered** [tannerlinsley/react-query-devtools#73]
Container height should be saved in local storage 

![](https://i.imgur.com/vhltxlb.gif)

**Comment by Tuaev** [comment]
Is there a way to set the default size of the window? It takes up way to much space.

**Comment by Tuaev** [comment]
You can add styles to the panelProps object. 

Something like this. `<ReactQueryDevtools panelProps={{ style: { height: '300px' } }} />`

**Comment by tannerlinsley** [comment]
Fixed in v3
