### ISSUE TITLE
Resizing dev tools should (maybe) trigger a window resize event?

### ISSUE THREAD

**Issue by mturley** [tannerlinsley/react-query-devtools#75]
Some layouts in an app I'm working on rely on the window `resize` event to recalculate some sizing and positioning (I know, I know, it should be CSS). When I shrink the dev tools I end up with some extra whitespace below my app and it looks broken until I resize the whole window.

If not the default, maybe there could be a `triggerEventOnResize` prop or something like that.

**Comment by tannerlinsley** [comment]
This should be fixed in v3
