### ISSUE TITLE
Not working with react-query@3

### ISSUE THREAD

**Issue by rek** [tannerlinsley/react-query-devtools#78]
Couldn't find any other information about this other than: https://github.com/tannerlinsley/react-query/discussions/1210

Has anything started on this front?

**Comment by TkDodo** [comment]
from what I can see, we "only" need to replace the usages of queryCache with the new `QueryClient`:

https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#queryclient

I can take a stab at making a PR, but there is no `next` branch yet or anything 🤔
