### ISSUE TITLE
Rem font size

### ISSUE THREAD

**Issue by nir905** [tannerlinsley/react-query-devtools#80]
Hi,

in my project, I've initialized the font size of html to be `1px` so I can use `rem` in all other places instead of `px`.

The result:

![image](https://user-images.githubusercontent.com/29302746/98686751-9a2f4d80-2371-11eb-8c3e-9441f9de2653.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/29302746/98687129-0f9b1e00-2372-11eb-87cd-920cd1fdc94a.png)

**Comment by tannerlinsley** [comment]
If this is still an issue, please open in the React Query repository
