### ISSUE TITLE
How to use with rollup?

### ISSUE THREAD

**Issue by lukemorales** [tannerlinsley/react-query-devtools#83]
I'm trying to build my app in which I'm using RQDevtools to see my queries but when I'm  trying to build my app with rollup, i get this error:
`Error: 'ReactQueryDevtools' is not exported by node_modules/react-query-devtools/index.js, imported by src/index.tsx`

I know it's not visible/available in production mode, but I don't want to have to remove the import and the component everytime I need to build my app. Is there a solution?

**Comment by tannerlinsley** [comment]
v3 imports have now changed. Please reference the core react-query docs: https://react-query.tanstack.com/devtools
