### ISSUE TITLE
Queries in dev tools have white text on white background

### ISSUE THREAD

**Issue by kouliavtsev** [tannerlinsley/react-query-devtools#84]
In Chrome when I try to inspect the queries they are a bit hard to see since the text and background are both white.

![Screenshot 2020-12-01 at 09 14 18](https://user-images.githubusercontent.com/1392575/100714533-2acbdd00-33b6-11eb-9d41-deed9541ec0d.png)

**Comment by TkDodo** [comment]
This doesn't happen for me or in the examples. Maybe you have some global styles that overwrite the text-color? The devtools are just a div that is inserted into your app, so they are definitely affected by global styles :)
