### ISSUE TITLE
Consider explicit inclusion of `ReactQueryDevtools`

### ISSUE THREAD

**Issue by zaiste** [tannerlinsley/react-query-devtools#85]
Would it be possible to change a bit the inclusion behviour of `ReactQueryDevtools` ? 

Right now, there is a implicit conditional in `react-query-devtools` that depends on `NODE_ENV`. This slightly breaks the ESM tooling e.g. snowpack. The generated bundle makes `ReactQueryDevtools` **always** `null` (cf. https://github.com/snowpackjs/snowpack/discussions/1312)

I propose to make make the inclusion explicit in the enduser codebase e.g.

```tsx
<>
   {* actual app *}
   {isProduction && <ReactQueryDevtools />}
</> 
```

This is also somehow related to #82.

**Comment by tannerlinsley** [comment]
I would rather find a way to make it compatible for snowpack so it’s automatic. Otherwise, this would degrade the experience for everyone else just to satisfy the snowpack env.

**Comment by zaiste** [comment]
Yes, I understand. We're discussing it [here](https://github.com/snowpackjs/snowpack/discussions/1312#discussioncomment-147510) for snowpack. I believe this problem will also affect those using other building tools e.g. `esbuild`.

Maybe we close this issue for the time being and reopen if the situation clarifies ?

**Comment by tannerlinsley** [comment]
Yeah I think that’s fine. You could also bypass the prod/dev-safe index import and just import the prod version yourself and do the interpolation you suggested.
