### ISSUE TITLE
Remeber devtools height on page refresh please please please!!!!!

### ISSUE THREAD

**Issue by sahilrajput03** [tannerlinsley/react-query-devtools#89]
When i chnage the height of dev tools and refresh the page, its very disgusting experience to change its height again to desired height, i am sure other people would be having this same frustration at many times.., plesase fix this., as to store the height in localStore in browser.

**Comment by tannerlinsley** [comment]
Please use the new built in devtools for v3 . And also avoid superfluous language in issue titles and descriptions in the future.
