### ISSUE TITLE
Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by brumm** [tannerlinsley/react-query-devtools#9]
Hey,

rendering a `<ReactQueryDevtools />` in our App causes this warning to be logged, after triggering a useQuery: 
`Warning: Cannot update a component from inside the function body of a different 
component.`

The stack trace points to this callsite, line 182: https://github.com/tannerlinsley/react-query-devtools/blob/49c23295584476437d24120e2b06b602a27e86e0/src/index.js#L180-L184

While we _are_ setting state there, it does not seem like it matches the conditions for the warning. The state being set originated inside the same component, and it's not in a useEffect, not during render. Not sure what that's about, maybe a false positive?

There's a lengthy issue thread over on facebook/react about this: https://github.com/facebook/react/issues/18178

Versions:
```
"react-dom": "^16.13.0",
"react-query": "^1.0.24",
"react-query-devtools": "^1.0.12",
```

**Comment by tannerlinsley** [comment]
React Query itself was just updated to fix a similar issue. Can you confirm that this still exists with the latest version of RQ?
